name: PortalsPE
main: luca28pet\PortalsPE\Main
api: 5.3.0
version: 3.0.0
authors: [fernanACM, luca28pet]
description: A portals plugin
permissions:
  portalspe:
    default: false
  portalspe.portal:
    default: false
  portalspe.command:
    default: false
  portalspe.command.portal:
    default: op